routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MyTransactionController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductGalleryController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\UserController;

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//  route for landing
// Route::view('/form/transaction', 'landingpage.pages.form');

Route::view('/contact', 'landingpage.pages.contact')->name('contact');
Route::get('/', [ShopController::class, 'index'])->name('index');
Route::get('/shop_list', [ShopController::class, 'shop_list'])->name('shop_list');
Route::get('/shop', [ShopController::class, 'search'])->name('search');
route::get('/details/{slug}', [ShopController::class, 'details'])->name('detail');

// valdiasi untuk landing jadi harus login dulu untuk mengakses route ini
Route::middleware(['auth:sanctum', 'verified'])->group(function () {

    Route::get('/cart', [ShopController::class, 'cart'])->name('cart');
    // Route::get('/cart', ShopController::class);

    // untuk buat order cart
    Route::post('/cart/{id}', [ShopController::class, 'tambahCart'])->name('tambahCart');

    Route::delete('/cart/{id}', [ShopController::class, 'hapusCart'])->name('hapusCart');

    Route::post('/checkout', [ShopController::class, 'checkout'])->name('checkout');

    Route::get('/checkout/success', [ShopController::class, 'success'])->name('success');

    Route::resource('/register-success', RegisterController::class);


});

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');


// Ini Route untuk dashboard
Route::middleware(['auth:sanctum', 'verified'])->name('dashboard.')->prefix('dashboard')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('index');

        Route::middleware(['user'])->group(function() {
            Route::resource('my-transaction', MyTransactionController::class);
        });



    // Ini hanya dpa di akses oleh admin
    Route::middleware(['admin'])->group(function() {
        Route::resource('products', ProductController::class);
        Route::resource('products.gallery', ProductGalleryController::class)->shallow()->only([
            'index', 'create', 'store', 'destroy'
        ]);
        Route::resource('transaction', TransactionController::class);
        Route::resource('user', UserController::class);
    });

});

// route for generate pdf
Route::get('/generate-pdf', [TransactionController::class, 'downloadPDF']);
Route::get('/generate-excel', [TransactionController::class, 'downloadEXCEL']);
Route::view('error', 'landingpage.components.404');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(Request $request)
    {
        return view('dashboard');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/pages/dashboard/gallery/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Product / {{ $product->name }} / Gallery / Upload Photos
        </h2>
    </x-slot>

    @include('sweetalert::alert')

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div>
                @if ($errors->any())
                    <div class="mb-5" role="alert">
                        <div class="bg-red-500 text-white font-bold rounded-t px-4 py-2">
                            There's something wrong!
                        </div>
                        <div class="border border-t-0 border-red-400 rounded-b bg-red-100 px-4 py-3 text-red-700">
                            <p>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                            </p>
                        </div>
                    </div>
                @endif
                <div class="mb-8 flex justify-end">
                        <a href="{{ route('dashboard.products.gallery.index', $product->id) }}"
                            class="bg-indigo-700 hover:bg-blue-500 text-white font-bold py-2  px-4 rounded shadow-lg">
                            <i class="fa fa-chevron-left" aria-hidden="true"></i> back
                            </a>
                </div>
                <form action="{{ route('dashboard.products.gallery.store', $product->id) }}" method="POST"
                    class="w-full" enctype="multipart/form-data">
                    @csrf
                    <div class="flex flex-wrap -mx-3  mb-6">
                        <div class="w-full px-3">
                            <label
                                class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Name</label>
                            {{-- files di dapat dari validari request --}}
                            <input type="file" name="files[]"
                                class="block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-y-gray-500"
                                placeholder="Upload Photos" multiple accept="image/*">
                        </div>
                    </div>

                    <div class="flex flex-wrap -mx-3 mb-6">
                        <div class="w-full px-3">
                            <button type="submit"
                                class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded shadow-lg">
                                <i class="fa fa-floppy-o" aria-hidden="true"></i> Save Photo gallery
                            </button>
                        </div>
                    </div>


                </form>

            </div>
        </div>
    </div>

</x-app-layout>

resources/views/pages/dashboard/gallery/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Product / {{ $product->name }} / Gallery
        </h2>
    </x-slot>

    <x-slot name="script" >
        <script>
            // AJAX Datatables
            var datatable = $('#crudTable').DataTable({
                ajax: {
                    url: '{!! url()->current() !!}'
                },
                columns: [{
                        data: 'id',
                        name: 'id',
                        width: '5%',

                    },
                    {
                        data: 'url',
                        name: 'url',
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false,
                        width: '25%'
                    }

                ]
            })
        </script>
    </x-slot>

    @include('sweetalert::alert')

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="mb-10 flex justify-between">
                <a href="{{ route('dashboard.products.gallery.create', $product->id) }}"
                    class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded shadow-lg">
                    <i class="fa fa-plus" aria-hidden="true"></i> Upload Photos
                </a>
                <a href="{{ route('dashboard.products.index') }}"
                    class="bg-indigo-700 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded shadow-lg">
                    <i class="fa fa-chevron-left" aria-hidden="true"></i> back
                </a>
            </div>
            <div class="shadow overflow-hidden sm-rounded-md">
                <div class="px-4 py-5 bg-white sm:p-6">
                    <table id="crudTable">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Photo</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</x-app-layout>